services:
  - type: web
    name: reminder-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///reminders.db
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_NAME
        sync: false
      - key: DEFAULT_RECIPIENT_EMAIL
        sync: false 