services:
  - type: web
    name: reminder-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: reminder-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: reminder-cache
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_NAME
        sync: false
      - key: DEFAULT_RECIPIENT_EMAIL
        sync: false

  - type: redis
    name: reminder-cache
    ipAllowList: []
    plan: free

  - type: worker
    name: reminder-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A tasks.celery worker --loglevel=info
    envVars:
      - fromService:
          type: redis
          name: reminder-cache
          property: connectionString
        key: REDIS_URL

  - type: worker
    name: reminder-scheduler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A tasks.celery beat --loglevel=info
    envVars:
      - fromService:
          type: redis
          name: reminder-cache
          property: connectionString
        key: REDIS_URL

databases:
  - name: reminder-db
    databaseName: reminder
    plan: free 